version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: Lucky
      POSTGRES_PASSWORD: 58365836
      POSTGRES_DB: Feedback
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    
volumes:
  pgdata:
    driver: local